version: "3.9"
services:
  postgres-ruby:
    image: postgres:14.1-alpine
    container_name: postgres-ruby
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kapaoilruby_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  api:
    build: .
    command: 'bundle exec rails s -p'
    container_name: api
    depends_on:
      - postgres-ruby
    ports:
      - "5000:5000"
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres-ruby:5432/kapaoilruby_DB?schema=public"
    volumes:
    - .:/app:cached

volumes:
  postgres-data:
