# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: 15

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
  database: Kapa_store_ruby_api_production
  username: Kapa_store_ruby_api
  password: <%= ENV["KAPA_STORE_RUBY_API_DATABASE_PASSWORD"] %>
